import json
import uuid
import logging
from datetime import datetime
from flask_login import current_user
from rq import Queue
from app.extensions import db
from app.models import TrainingJob, MLModel, SystemSetting
from app.tasks.training_worker import execute_training_job
from app.services.audit_service import AuditService
from app.services.metrics_service import MetricsService

logger = logging.getLogger("brain_service")

class BrainService:
    @staticmethod
    def start_training_job(params: dict) -> str:
        """Details: Spawn a background worker to train models (via RQ)."""
        # Create Job Record
        job = TrainingJob(
            status="pending",
            logs=f"Job initialized with params: {params}",
            result_metrics={}
        )
        try:
            db.session.add(job)
            db.session.commit()
        except Exception as e:
            # JIT Repair: If ID autoincrement fails (Postgres NotNullViolation/Sequence issue)
            if "NotNullViolation" in str(e) or "null value in column \"id\"" in str(e):
                logger.warning("⚠️ Encountered ID error. Attempting JIT DB Repair...")
                db.session.rollback()
                
                try:
                    from sqlalchemy import text
                    with db.engine.connect() as conn:
                        # Force fix sequence
                        conn.execute(text("CREATE SEQUENCE IF NOT EXISTS training_job_id_seq"))
                        conn.execute(text("ALTER TABLE training_job ALTER COLUMN id SET DEFAULT nextval('training_job_id_seq')"))
                        conn.execute(text("ALTER SEQUENCE training_job_id_seq OWNED BY training_job.id"))
                        # Sync
                        result = conn.execute(text("SELECT COALESCE(MAX(id), 0) FROM training_job"))
                        max_id = result.scalar()
                        conn.execute(text(f"SELECT setval('training_job_id_seq', {max_id + 1}, false)"))
                        conn.commit()
                        logger.info("✅ JIT DB Repair Complete. Retrying insert...")
                        
                    # Retry Insert
                    db.session.add(job)
                    db.session.commit()
                    
                except Exception as fix_err:
                    logger.error(f"❌ JIT Repair Failed: {fix_err}")
                    raise e
            else:
                logger.error(f"Failed to create training job record: {e}")
                db.session.rollback()
                raise e
        
        # Audit Log
        try:
            user_id = current_user.id if current_user and current_user.is_authenticated else "system"
            AuditService.log_event(user_id, "brain.train.start", f"Job ID: {job.id}")
        except Exception as e:
            logger.warning(f"Audit log validation failed: {e}")

        # Enqueue Job (Isolated Task)
        try:
            from app.extensions import redis_client
            if not redis_client:
                # One last retry to fetch from app context if possible or just fail
                raise Exception("Redis unavailable - cannot enqueue job")
                
            q = Queue('training_jobs', connection=redis_client)
            # Increase timeout to 10 minutes for ML training (default is 180s)
            q.enqueue(execute_training_job, str(job.id), params, job_timeout=600)
            logger.info(f"Job {job.id} enqueued to 'training_jobs'.")
            
        except Exception as e:
            logger.error(f"Failed to enqueue training job: {e}")
            job.status = "failed"
            job.logs += f"\nFailed to enqueue worker: {e}"
            db.session.commit()
            MetricsService.record_job_failure()
            return str(job.id)
        
        return str(job.id)

    @staticmethod
    def start_auto_training_job(symbol):
        """
        Start a comprehensive AutoML Grid Search training job.
        
        Args:
            symbol (str): Trading pair symbol (e.g. BTCUSDT)
            
        Returns:
            str: Job ID
        """
        params = {
            "symbol": symbol,
            "mode": "auto_grid_search"
        }
        
        # Create Job Record (Valid fields only)
        # Note: ID is auto-generated by DB
        job = TrainingJob(
            status="queued",
            logs=f"AutoML Job initialized for {symbol}\nParams: {params}",
            result_metrics=params, # Storing params in metrics for reference
            created_at=datetime.utcnow()
        )
        
        # Commit to get the ID
        try:
            db.session.add(job)
            db.session.commit()
        except Exception as e:
            logger.error(f"Failed to create DB record for AutoML: {e}")
            db.session.rollback()
            raise e
            
        # Use DB ID as the Job ID
        job_id = str(job.id)
        
        # Enqueue Job
        try:
            from app.extensions import redis_client
            if not redis_client:
                 raise Exception("Redis unavailable")
                 
            q = Queue('training_jobs', connection=redis_client)
            # HIGH TIMEOUT: 1 hour for grid search
            q.enqueue(
                "app.tasks.training_worker.execute_auto_training_job",
                args=(job_id, params), 
                job_id=job_id,
                job_timeout=3600
            )
            logger.info(f"Queued AutoML job {job.id} (Task {job_id})")
        except Exception as e:
            logger.error(f"Failed to enqueue AutoML job: {e}")
            job.status = "failed"
            job.logs = f"Enqueue failed: {e}"
            db.session.commit()
            raise e
            
        return job_id

    @staticmethod
    def get_brain_status():
        """Connects to Redis/DB to get live brain status."""
        from app.core.system_state import SystemStateManager
        
        # 1. Get Trusted System State (SSOT)
        sys_state = SystemStateManager.get_status()
        is_online = sys_state.get("status") == "ONLINE"
        
        # 2. Check Pause State
        paused = False
        from app.extensions import redis_client
        if redis_client:
            try:
                # Still check raw pause switch as it might be separate from heartbeat
                val = redis_client.get("brain:signals:paused")
                if val:
                    val_str = val.decode() if isinstance(val, bytes) else str(val)
                    paused = (val_str == "1")
            except Exception:
                pass
        
        # 3. Active Models (DB)
        active_models = MLModel.query.filter_by(status="active").all()
        active_list = []
        for am in active_models:
             s_name = am.strategy.name if am.strategy else "Legacy/Global"
             active_list.append(f"{s_name}: {am.version}")
             
        active_display = ", ".join(active_list) if active_list else "No Active Brains"
        
        # 4. Risk Stats
        from app.services.portfolio_risk_service import PortfolioRiskService
        
        # Determine Final Status Text
        status_text = "OFFLINE"
        if is_online:
            status_text = "PAUSED" if paused else "OCULAR_LINK_ESTABLISHED"
        
        return {
            "status": status_text,
            "active_model": active_display,
            "inference_heartbeat": "HEALTHY" if is_online else "OFFLINE", 
            "market_regime": "SCANNING", # No more hardcoded ACCUMULATION
            "strategies_active": len(active_list),
            "risk_metrics": {
                "max_leverage": PortfolioRiskService.MAX_GLOBAL_LEVERAGE,
                "max_correlation": PortfolioRiskService.MAX_CORRELATED_POSITIONS
            }
        }

    @staticmethod
    def pause_brain(paused: bool):
        """Global Kill Switch for Signals."""
        from app.extensions import redis_client
        if not redis_client:
            return False
        try:
            val = "1" if paused else "0"
            redis_client.set("brain:signals:paused", val)
            
            # Audit Log
            try:
                user_id = current_user.id if current_user and current_user.is_authenticated else "system"
                action = "brain.signals.pause" if paused else "brain.signals.resume"
                AuditService.log_event(user_id, action, "Emergency Switch")
            except Exception:
                pass
                
            return True
        except Exception:
            return False

    @staticmethod
    def activate_model(model_id, confirmation_phrase=None, is_rollback=False):
        """Atomic swap of active model with governance checks."""
        # 1. Verification
        if not is_rollback:
            EXPECTED_PHRASE = "I AUTHORIZE DEPLOYMENT"
            if confirmation_phrase != EXPECTED_PHRASE:
                try:
                    user_id = current_user.id if current_user and current_user.is_authenticated else "system"
                    AuditService.log_event(user_id, "brain.model.activate_failure", f"Model ID: {model_id} - Incorrect phrase", status="failure")
                except Exception:
                    pass
                return False, "Incorrect confirmation phrase"

        target = MLModel.query.get(model_id)
        if not target: 
            return False, "Model not found"
            
        if target.status == "deprecated":
            return False, "Cannot activate a deprecated model"
            
        # Risk Gatekeeping (Phase 4.2) - Skip for rollback? Maybe safer to allow rollback even if metrics missing (e.g. legacy model)
        if not is_rollback:
            metrics = target.metrics or {}
            if "max_drawdown" not in metrics or "win_loss_ratio" not in metrics:
                 return False, "Model unsafe: Missing risk metrics (Drawdown/WinLoss)"
            
            # Guardrail: Prevent activation if Max DD > 80% (Absolute blowing up)
            max_dd = float(metrics.get("max_drawdown", 100.0))
            if max_dd > 80.0:
                 return False, f"Model RISKY: Max Drawdown is {max_dd}%. Activation rejected."
        
        # 2. Deactivate current & Save Previous
        # Phase 5.1: Multi-Strategy Support
        # Only deactivate the active model FOR THIS STRATEGY
        from app.models import SystemSetting
        
        # Determine strategy context
        strat_id = target.strategy_id
        
        # Scope by Symbol (Enable Multi-Symbol Parallel)
        logger.info(f"Target Symbol: '{target.symbol}' | ID: {target.id}")
        
        if target.symbol:
            # Strict Filter: Active + Same Strategy + Same Symbol
            query = MLModel.query.filter(
                MLModel.status == "active",
                MLModel.strategy_id == strat_id,
                MLModel.symbol == target.symbol
            )
        else:
             logger.warning(f"Target model {target.id} has NO SYMBOL! This will cause global replacement.")
             # Fallback to current query which is strategy-scoped but symbol-agnostic
             query = MLModel.query.filter_by(status="active")
             if strat_id:
                 query = query.filter_by(strategy_id=strat_id)
             else:
                 # If no strategy (Legacy), find active legacy models (null strategy)
                 query = query.filter(MLModel.strategy_id.is_(None))
            
        current = query.first()
        if current:
             logger.info(f"Found existing active model to archive: {current.id} ({current.symbol})")
        else:
             logger.info(f"No conflicting active model found for symbol '{target.symbol}'")
        
        if current:
            # Check if we are activating the SAME model
            if current.id == target.id:
                return False, "Model is already active"
            
            # Save ID for rollback
            # We need scoped rollback keys per strategy?
            # For now, keep global key but maybe append strategy ID to key name?
            # Or just use global for simplicity in UI for now (last activated model)
            # Better: `brain_previous_active_model_id_{strat_id}`
            key = f"brain_previous_active_model_id_{strat_id}" if strat_id else "brain_previous_active_model_id"
            SystemSetting.set_value(key, str(current.id))
            
            current.status = "archived"
        
        # 3. Activate new
        target.status = "active"
        db.session.commit()
        
        # 4. Sync to Redis for SignalPublisher access
        from app.extensions import redis_client
        if redis_client:
            try:
                redis_client.set("brain:active_model_version", target.version)
            except Exception as e:
                pass 
        
        # Publish Hot-Reload Signal
        # This tells the MarketDataService (running in a separate process/container)
        # to immediately reload the inference engine models without a full restart.
        try:
            import json
            import time
            payload = json.dumps({
                "model_id": target.id,
                "strategy_id": strat_id,
                "timestamp": time.time(),
                "action": "activate"
            })
            redis_client.publish("brain:model_reload", payload)
            logger.info(f"Published hot-reload signal for model {target.version}")
        except Exception as e:
            logger.error(f"Failed to publish hot-reload signal: {e}") 
        
        # 5. Audit Log (Success)
        try:
            user_id = current_user.id if current_user and current_user.is_authenticated else "system"
            action = "brain.model.rollback" if is_rollback else "brain.model.activate"
            AuditService.log_event(user_id, action, f"Activated Model: {target.version}", status="success")
        except Exception:
            pass
            
        return True, "Model activated successfully"

    @staticmethod
    def rollback_model(strategy_id=None):
        """Emergency revert to previous model."""
        from app.models import SystemSetting
        
        key = f"brain_previous_active_model_id_{strategy_id}" if strategy_id else "brain_previous_active_model_id"
        prev_id_str = SystemSetting.get_value(key)
        
        if not prev_id_str:
            return False, "No previous model recorded for this strategy"
            
        try:
            prev_id = int(prev_id_str)
        except:
             return False, "Invalid previous model ID"
             
        # Reuse activate logic with rollback flag
        return BrainService.activate_model(prev_id, is_rollback=True)

    @staticmethod
    def set_model_status(model_id, status):
        """Update lifecycle status (e.g. deprecate)."""
        model = MLModel.query.get(model_id)
        if not model:
            return False, "Model not found"
            
        if model.status == "active" and status != "active":
             return False, "Cannot change status of ACTIVE model directly. Use activate/rollback."
             
        model.status = status
        db.session.commit()
        
        user_id = current_user.id if current_user and current_user.is_authenticated else "system"
        AuditService.log_event(user_id, "brain.model.status_change", f"Model {model.version} -> {status}")
        
        return True, f"Status updated to {status}"

    @staticmethod
    def archive_model(model_id):
        """Archive a model (prevent it from being activated)."""
        target = MLModel.query.get(model_id)
        if not target: return False
        
        if target.status == "active":
            return False # Cannot archive active model directly, must activate another first
            
        target.status = "archived"
        db.session.commit()
        
        # Audit Log
        try:
            user_id = current_user.id if current_user and current_user.is_authenticated else "system"
            AuditService.log_event(user_id, "brain.model.archive", f"Model: {target.version}")
        except Exception:
            pass
            
        return True

    @staticmethod
    def run_backtest(params: dict) -> dict:
        """
        Run a historical backtest (Simulation).
        Does NOT execute trades. Returns simulation result.
        """
        # In Phase 1, we simulate the backtest result
        # Phase 2: Connect to Backtest Engine
        
        symbol = params.get("symbol", "BTCUSDT")
        days = int(params.get("days", 30))
        
        # Audit Log
        try:
            user_id = current_user.id if current_user and current_user.is_authenticated else "system"
            AuditService.log_event(user_id, "brain.simulate", f"{symbol} for {days} days")
        except Exception:
            pass

        # Simulation Result
        return {
            "symbol": symbol,
            "period": f"{days} days",
            "total_trades": 142,
            "win_rate": 64.5,
            "profit_factor": 1.8,
            "total_pnl_percent": 18.4,
            "drawdown": 4.2
        }

    @staticmethod
    def pause_strategy(strategy_id, reason="manual"):
        """Pause a specific strategy (Circuit Breaker)."""
        from app.models import Strategy
        s = Strategy.query.get(strategy_id)
        if not s: return False
        
        s.status = "paused_risk"
        db.session.commit()
        
        try:
             user_id = current_user.id if current_user and current_user.is_authenticated else "system"
             AuditService.log_event(user_id, "strategy.pause", f"Paused {s.name}: {reason}", status="warning")
        except: pass
        
        return True

    @staticmethod
    def resume_strategy(strategy_id):
        """Resume a paused strategy."""
        from app.models import Strategy
        s = Strategy.query.get(strategy_id)
        if not s: return False
        
        s.status = "active"
        # Reset health checks
        s.consecutive_losses = 0 
        db.session.commit()
        
        try:
             user_id = current_user.id if current_user and current_user.is_authenticated else "system"
             AuditService.log_event(user_id, "strategy.resume", f"Resumed {s.name}")
        except: pass
        
        return True

    @staticmethod
    def deactivate_model(model_id):
        """Force deactivate an active model (Stop Trading)."""
        target = MLModel.query.get(model_id)
        if not target: return False, "Model not found"
        
        if target.status != "active":
            return False, "Model is not active"
            
        target.status = "archived"
        db.session.commit()
        
        # Audit Log
        try:
            user_id = current_user.id if current_user and current_user.is_authenticated else "system"
            AuditService.log_event(user_id, "brain.model.deactivate", f"Deactivated {target.version} ({target.symbol})")
        except: pass
        
        return True, "Model deactivated successfully"

    @staticmethod
    def delete_model(model_id):
        """Permanently delete a model and its file."""
        import os
        
        target = MLModel.query.get(model_id)
        if not target: return False, "Model not found"
        
        if target.status == "active":
            return False, "Cannot delete an ACTIVE model. Activate another model first."
            
        file_path = target.file_path
        
        # Delete from DB
        try:
            db.session.delete(target)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            return False, f"DB Error: {e}"
            
        # Delete file
        if file_path and os.path.exists(file_path):
            try:
                os.remove(file_path)
            except Exception as e:
                # Log but don't fail, as DB is already cleaned
                logger.warning(f"Failed to delete model file {file_path}: {e}")
                
        # Audit Log
        try:
            user_id = current_user.id if current_user and current_user.is_authenticated else "system"
            AuditService.log_event(user_id, "brain.model.delete", f"Deleted model {model_id}")
        except: pass
        
        return True, "Model deleted permanently"
