"""Add payment_settings table

Revision ID: 1012cecb3be5
Revises: 
Create Date: 2025-12-09 01:04:22.922213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1012cecb3be5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_tier_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_tier_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('headline', sa.VARCHAR(length=120), nullable=True),
    sa.Column('badge', sa.VARCHAR(length=50), nullable=True),
    sa.Column('included_packages', sqlite.JSON(), nullable=True),
    sa.Column('role_options', sqlite.JSON(), nullable=True),
    sa.Column('limits', sqlite.JSON(), nullable=True),
    sa.Column('cta_label', sa.VARCHAR(length=80), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    # ### end Alembic commands ###
