"""add_audit_ip

Revision ID: 1a529c60ac1f
Revises: 75efca44cc22
Create Date: 2026-01-20 19:51:02.315089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a529c60ac1f'
down_revision = '75efca44cc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
