"""add reseller table

Revision ID: 20260120212500
Revises: 20260120204509
Create Date: 2026-01-20 21:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260120212500'
down_revision = '20260120204509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('branding_config', sa.JSON(), nullable=True),
    sa.Column('limits_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reseller_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('reseller_role', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_user_reseller', 'reseller', ['reseller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_reseller', type_='foreignkey')
        batch_op.drop_column('reseller_role')
        batch_op.drop_column('reseller_id')

    op.drop_table('reseller')
    # ### end Alembic commands ###
