"""add candles table

Revision ID: 20260120204509
Revises: 1a529c60ac1f
Create Date: 2026-01-20 20:45:09.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260120204509'
down_revision = '1a529c60ac1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('time', 'symbol', 'interval')
    )
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.create_index('ix_candles_time_symbol', ['time', 'symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candles', schema=None) as batch_op:
        batch_op.drop_index('ix_candles_time_symbol')
    op.drop_table('candles')
    # ### end Alembic commands ###
