"""Add balance and portfolio_value to User model

Revision ID: 51036a4f34f2
Revises: 1012cecb3be5
Create Date: 2025-12-10 23:39:56.130384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51036a4f34f2'
down_revision = '1012cecb3be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('portfolio_value')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
