"""Add account lockout fields

Revision ID: 5430cb240c91
Revises: e2eb5b81d252
Create Date: 2025-12-11 11:30:54.694583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5430cb240c91"
down_revision = "e2eb5b81d252"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("failed_login_attempts", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("locked_until", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("locked_until")
        batch_op.drop_column("failed_login_attempts")

    # ### end Alembic commands ###
