"""fix_usertrade_drift_batch

Revision ID: 75efca44cc22
Revises: 9dd5ece51ca1
Create Date: 2026-01-20 19:44:03.659858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75efca44cc22'
down_revision = '9dd5ece51ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('role')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('user_portfolio', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('avg_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('current_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('pnl',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('pnl_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('max_position_size',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(1000.0)'))
        batch_op.alter_column('stop_loss',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
        batch_op.alter_column('take_profit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
        batch_op.alter_column('total_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(10000.0)'))
        batch_op.alter_column('available_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(10000.0)'))
        batch_op.alter_column('total_profit_loss',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('daily_pnl',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('open_positions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.drop_index(batch_op.f('ix_user_portfolio_user_id'))

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_user_subscription_user_id'))

    with op.batch_alter_table('user_trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trade_group_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('client_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exchange', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('margin_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True))
        batch_op.add_column(sa.Column('is_paper', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
        batch_op.alter_column('entry_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
        batch_op.alter_column('exit_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('pnl',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('confidence_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True)
        batch_op.alter_column('cost_basis',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('realized_gains',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_index(batch_op.f('ix_user_trade_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_trade_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('realized_gains',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('cost_basis',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('confidence_score',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('pnl',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('exit_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('entry_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.drop_column('details')
        batch_op.drop_column('reason')
        batch_op.drop_column('is_paper')
        batch_op.drop_column('realized_pnl')
        batch_op.drop_column('margin_type')
        batch_op.drop_column('exchange')
        batch_op.drop_column('client_order_id')
        batch_op.drop_column('order_id')
        batch_op.drop_column('trade_group_id')

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscription_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('user_portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_portfolio_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('open_positions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('daily_pnl',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_profit_loss',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('available_balance',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(10000.0)'))
        batch_op.alter_column('total_balance',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(10000.0)'))
        batch_op.alter_column('take_profit',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('stop_loss',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('max_position_size',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(1000.0)'))
        batch_op.alter_column('pnl_percent',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('pnl',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('avg_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'viewer'"), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###
