"""baseline schema

Revision ID: ae092e49e678
Revises: 
Create Date: 2026-01-13 04:02:30.964640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'ae092e49e678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Make creation idempotent: avoid creating enum type twice
    bind = op.get_bind()
    insp = inspect(bind)
    # PostgreSQL enum type check
    try:
        enum_exists = bool(bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'roleenum'")).fetchone())
    except Exception:
        enum_exists = False
    if not enum_exists:
        op.execute(sa.text("CREATE TYPE roleenum AS ENUM ('admin', 'trader', 'viewer')"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False, primary_key=True),  # type: ignore
        sa.Column('username', sa.String(length=150), nullable=False, unique=True),
        sa.Column('email', sa.String(length=150), nullable=False, unique=True, index=True),
        sa.Column('password_hash', sa.String(length=150), nullable=False),
        sa.Column('role', sa.Enum('admin', 'trader', 'viewer', name='roleenum'), nullable=False, default='viewer'),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('email_verified', sa.Boolean, default=False),
        sa.Column('created_at', sa.DateTime, nullable=False),
        sa.Column('last_login_at', sa.DateTime, nullable=True),
        sa.Column('last_ip', sa.String(length=45), nullable=True),
        sa.Column('failed_login_count', sa.Integer, default=0),
        sa.Column('locked_until', sa.DateTime, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
