"""Add email verification and password reset fields

Revision ID: e2eb5b81d252
Revises: 51036a4f34f2
Create Date: 2025-12-11 11:28:08.000805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2eb5b81d252"
down_revision = "51036a4f34f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email_verified", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("email_verification_token", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("email_verification_expires", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("password_reset_token", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("password_reset_expires", sa.DateTime(), nullable=True)
        )
        batch_op.create_unique_constraint(
            "uq_email_verification_token", ["email_verification_token"]
        )
        batch_op.create_unique_constraint(
            "uq_password_reset_token", ["password_reset_token"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("uq_password_reset_token", type_="unique")
        batch_op.drop_constraint("uq_email_verification_token", type_="unique")
        batch_op.drop_column("password_reset_expires")
        batch_op.drop_column("password_reset_token")
        batch_op.drop_column("email_verification_expires")
        batch_op.drop_column("email_verification_token")
        batch_op.drop_column("email_verified")

    # ### end Alembic commands ###
