#!/bin/bash
# Complete VPS Deployment Script for AI Trading Bot
# This script handles file transfer and Docker deployment

set -e  # Exit on any error

# Load configuration from production deploy.env
if [ -f "config/deploy.env.production" ]; then
    source config/deploy.env.production
    echo "✅ Using production configuration from config/deploy.env.production"
elif [ -f "config/deploy.env" ]; then
    source config/deploy.env
    echo "⚠️  Using legacy configuration from config/deploy.env"
else
    echo "❌ No config/deploy.env.production or config/deploy.env found. Please create production config."
    exit 1
fi

# Set defaults if not specified
VPS_HOST="${VPS_HOST:-your-vps-ip-or-domain}"
VPS_USER="${VPS_USER:-aibot}"
VPS_PATH="${VPS_PATH:-/home/aibot/ai-bot}"
VPS_SSH_PORT="${VPS_SSH_PORT:-22}"

echo "🚀 Starting complete AI Trading Bot deployment to VPS..."
echo "📍 Target: $VPS_USER@$VPS_HOST:$VPS_PATH"
echo "🔧 Production Config: $DATABASE_URL"
echo ""

# Check if required tools are installed
command -v rsync >/dev/null 2>&1 || { echo "❌ rsync is required but not installed. Aborting."; exit 1; }
command -v ssh >/dev/null 2>&1 || { echo "❌ ssh is required but not installed. Aborting."; exit 1; }

# Step 1: Sync files to VPS
echo "📦 Step 1: Syncing files to VPS..."
RSYNC_OPTS=(
    -az
    --progress
    --exclude ".git/"
    --exclude ".venv/"
    --exclude "__pycache__/"
    --exclude "*.pyc"
    --exclude "logs/"
    --exclude "bot_persistence/backups/"
    --exclude "*.pkl"  # Skip large model files initially
    --exclude "*.joblib"
    --exclude "htmlcov/"  # Skip coverage reports
    --exclude "node_modules/"  # Skip if any
)

rsync "${RSYNC_OPTS[@]}" -e "ssh -p $VPS_SSH_PORT" ./ "$VPS_USER@$VPS_HOST:$VPS_PATH/"

echo "✅ Files synced successfully!"
echo ""

# Step 2: Setup production environment on VPS
echo "🔧 Step 2: Setting up production environment on VPS..."

SSH_CMD="ssh -p $VPS_SSH_PORT $VPS_USER@$VPS_HOST"

# Create production config on VPS
echo "📝 Creating production configuration on VPS..."
$SSH_CMD "mkdir -p $VPS_PATH/config"
$SSH_CMD "cat > $VPS_PATH/config/deploy.env.production << 'EOF'
# Production Environment Configuration
# Generated by deployment script

# Database
DATABASE_URL=$DATABASE_URL

# Redis
REDIS_URL=$REDIS_URL

# Flask
FLASK_ENV=production
FLASK_APP=wsgi.py
SECRET_KEY=$SECRET_KEY

# Server
HOST=0.0.0.0
PORT=5000

# Logging
LOG_LEVEL=INFO
LOG_FILE=/var/log/ai-trading-bot.log

# Security
RATE_LIMIT_STORAGE_URL=$REDIS_URL

# Monitoring
PROMETHEUS_PORT=9090

# Trading
CIRCUIT_BREAKER_FAILURE_THRESHOLD=5
CIRCUIT_BREAKER_RECOVERY_TIMEOUT=300

# VPS Specific
VPS_HOST=$VPS_HOST
VPS_USER=$VPS_USER
VPS_PATH=$VPS_PATH
VPS_SSH_PORT=$VPS_SSH_PORT
EOF"

echo "✅ Production config created on VPS"
echo ""

# Step 3: Deploy Docker service on VPS
echo "⚙️  Step 3: Deploying Docker Compose on VPS..."

SSH_CMD="ssh -p $VPS_SSH_PORT $VPS_USER@$VPS_HOST"

$SSH_CMD "cd $VPS_PATH && docker compose -f docker-compose.prod.yml build --pull ai-trading-bot"
$SSH_CMD "cd $VPS_PATH && docker compose -f docker-compose.prod.yml up -d ai-trading-bot"

echo "✅ Docker deployment completed"
echo ""

echo "🎉 Deployment completed successfully!"
echo ""
echo "🌐 Your bot should be accessible at: http://$VPS_HOST:5000"
echo "📊 Prometheus metrics at: http://$VPS_HOST:9090/metrics"
echo ""
echo "📋 Useful commands on your VPS:"
echo "  Status: docker compose -f docker-compose.prod.yml ps ai-trading-bot"
echo "  Logs:   docker logs -f ai-trading-bot-prod"
echo "  Redeploy: cd $VPS_PATH && docker compose -f docker-compose.prod.yml up -d --build ai-trading-bot"
echo "  Metrics: curl http://localhost:9090/metrics"
echo ""
echo "🔧 To update the bot later, run this script again to sync and rebuild."
