#!/bin/bash
# Docker-based VPS Deployment Script for AI Trading Bot
# This script handles Docker deployment to VPS with SSH

set -e  # Exit on any error

# Load configuration from production deploy.env
if [ -f "config/deploy.env.production" ]; then
    source config/deploy.env.production
    echo "✅ Using production configuration from config/deploy.env.production"
elif [ -f "config/deploy.env" ]; then
    source config/deploy.env
    echo "⚠️  Using legacy configuration from config/deploy.env"
else
    echo "❌ No config/deploy.env.production or config/deploy.env found. Please create production config."
    exit 1
fi

# Set defaults if not specified
VPS_HOST="${VPS_HOST:-151.243.171.80}"
VPS_USER="${VPS_USER:-aibot}"
VPS_PATH="${VPS_PATH:-/home/aibot/ai-bot}"
VPS_SSH_PORT="${VPS_SSH_PORT:-22}"

echo "🐳 Starting Docker-based AI Trading Bot deployment to VPS..."
echo "📍 Target: $VPS_USER@$VPS_HOST:$VPS_PATH"
echo "🔧 Production Config: $DATABASE_URL"
echo ""

# Check if required tools are installed
command -v rsync >/dev/null 2>&1 || { echo "❌ rsync is required but not installed. Aborting."; exit 1; }
command -v ssh >/dev/null 2>&1 || { echo "❌ ssh is required but not installed. Aborting."; exit 1; }
command -v docker >/dev/null 2>&1 || { echo "❌ docker is required but not installed. Aborting."; exit 1; }

# Check if SSH password is provided
if [ -z "$SSH_PASSWORD" ]; then
    echo "🔑 Please provide SSH password for $VPS_USER@$VPS_HOST:"
    read -s SSH_PASSWORD
    echo ""
fi

# Export for use in SSH commands
export SSH_PASSWORD

# Function to run SSH commands with password
ssh_cmd() {
    local cmd="$1"
    echo "$SSH_PASSWORD" | ssh -p "$VPS_SSH_PORT" -o StrictHostKeyChecking=no "$VPS_USER@$VPS_HOST" "$cmd"
}

# Step 1: Sync files to VPS
echo "📦 Step 1: Syncing files to VPS..."
RSYNC_OPTS=(
    -az
    --progress
    --exclude ".git/"
    --exclude ".venv/"
    --exclude "__pycache__/"
    --exclude "*.pyc"
    --exclude "logs/"
    --exclude "bot_persistence/backups/"
    --exclude "*.pkl"  # Skip large model files initially
    --exclude "*.joblib"
    --exclude "htmlcov/"  # Skip coverage reports
    --exclude "node_modules/"  # Skip if any
    --exclude ".pytest_cache/"
)

rsync "${RSYNC_OPTS[@]}" -e "ssh -p $VPS_SSH_PORT -o StrictHostKeyChecking=no" ./ "$VPS_USER@$VPS_HOST:$VPS_PATH/"

echo "✅ Files synced successfully!"
echo ""

# Step 2: Setup production environment on VPS
echo "🔧 Step 2: Setting up production environment on VPS..."

# Create production config on VPS
echo "📝 Creating production configuration on VPS..."
ssh_cmd "mkdir -p $VPS_PATH/config"

# Create production environment file
cat > /tmp/deploy.env.production << 'EOF'
# Production Environment Configuration
# Generated by Docker deployment script

# Database
DATABASE_URL=postgresql://trading_user:secure_password_123@postgres:5432/trading_bot

# Redis
REDIS_URL=redis://redis:6379/0

# Flask
FLASK_ENV=production
FLASK_APP=wsgi.py
SECRET_KEY=l5rQc4-0AogmUdTZlktQFbeq1W2rpigv04dN1tjTY2GjM3lTqt6_8taZVde2u7hQ

# Server
HOST=0.0.0.0
PORT=5000

# Logging
LOG_LEVEL=INFO
LOG_FILE=/app/bot_persistence/logs/ai-trading-bot.log

# Security
RATE_LIMIT_STORAGE_URL=redis://redis:6379/0

# Monitoring
PROMETHEUS_PORT=9090

# Trading
CIRCUIT_BREAKER_FAILURE_THRESHOLD=5
CIRCUIT_BREAKER_RECOVERY_TIMEOUT=300

# Performance Settings
PERFORMANCE_CACHING_ENABLED=true
PERFORMANCE_BATCH_SIZE=1000
PERFORMANCE_MEMORY_LIMIT=512
PERFORMANCE_DB_POOL_SIZE=10

# Docker Environment
POSTGRES_PASSWORD=secure_password_123
GRAFANA_PASSWORD=admin123

# VPS Specific
VPS_HOST=151.243.171.80
VPS_USER=aibot
VPS_PATH=/home/aibot/ai-bot
VPS_SSH_PORT=22
EOF

# Upload config to VPS
scp -P "$VPS_SSH_PORT" -o StrictHostKeyChecking=no /tmp/deploy.env.production "$VPS_USER@$VPS_HOST:$VPS_PATH/config/deploy.env.production"

echo "✅ Production config created on VPS"
echo ""

# Step 3: Install Docker on VPS if not present
echo "🐳 Step 3: Ensuring Docker is installed on VPS..."

# Check if Docker is installed
if ! ssh_cmd "command -v docker >/dev/null 2>&1"; then
    echo "📦 Installing Docker on VPS..."
    ssh_cmd "curl -fsSL https://get.docker.com -o get-docker.sh"
    ssh_cmd "sudo sh get-docker.sh"
    ssh_cmd "sudo systemctl enable docker"
    ssh_cmd "sudo systemctl start docker"
    ssh_cmd "sudo usermod -aG docker $VPS_USER"
    echo "✅ Docker installed on VPS"
else
    echo "✅ Docker already installed on VPS"
fi

# Check if Docker Compose is installed
if ! ssh_cmd "command -v docker-compose >/dev/null 2>&1 || docker compose version >/dev/null 2>&1"; then
    echo "⚠️  Docker Compose not found. Please install Docker Compose manually on VPS:"
    echo "   sudo curl -L \"https://github.com/docker/compose/releases/latest/download/docker-compose-\$(uname -s)-\$(uname -m)\" -o /usr/local/bin/docker-compose"
    echo "   sudo chmod +x /usr/local/bin/docker-compose"
    echo ""
    echo "Or if you have sudo access, the script can try to install it."
    read -p "Do you have sudo access to install Docker Compose? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "🔑 Please provide sudo password for Docker Compose installation:"
        read -s SUDO_PASSWORD
        echo "$SUDO_PASSWORD" | ssh_cmd "sudo -S curl -L \"https://github.com/docker/compose/releases/latest/download/docker-compose-\$(uname -s)-\$(uname -m)\" -o /usr/local/bin/docker-compose"
        echo "$SUDO_PASSWORD" | ssh_cmd "sudo -S chmod +x /usr/local/bin/docker-compose"
        echo "✅ Docker Compose installed on VPS"
    else
        echo "❌ Docker Compose installation skipped. Please install manually and run deployment again."
        exit 1
    fi
else
    echo "✅ Docker Compose already available on VPS"
fi

echo ""

# Step 4: Deploy with Docker
echo "🚀 Step 4: Deploying with Docker on VPS..."

# Change to project directory and deploy
ssh_cmd "cd $VPS_PATH && docker compose -f docker-compose.prod.yml down || true"

# Build and deploy
ssh_cmd "cd $VPS_PATH && docker compose -f docker-compose.prod.yml build --no-cache"

# Start services
ssh_cmd "cd $VPS_PATH && docker compose -f docker-compose.prod.yml up -d"

# Wait for services to be healthy
echo "⏳ Waiting for services to be healthy..."
sleep 30

# Check if services are running
echo "📊 Checking service status..."
ssh_cmd "cd $VPS_PATH && docker compose -f docker-compose.prod.yml ps"

# Test health endpoint
echo "🏥 Testing application health..."
max_attempts=10
attempt=1
while [ $attempt -le $max_attempts ]; do
    if ssh_cmd "curl -f -s http://localhost:5000/health >/dev/null 2>&1"; then
        echo "✅ Application health check passed!"
        break
    fi
    echo "⏳ Health check attempt $attempt/$max_attempts..."
    sleep 10
    ((attempt++))
done

if [ $attempt -gt $max_attempts ]; then
    echo "❌ Application health check failed after $max_attempts attempts"
    ssh_cmd "cd $VPS_PATH && docker-compose -f docker-compose.prod.yml logs --tail=50"
    exit 1
fi

echo ""

# Step 5: Setup monitoring (optional)
echo "📊 Step 5: Setting up monitoring services..."

# Ask if user wants monitoring
read -p "Do you want to enable monitoring with Prometheus and Grafana? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ssh_cmd "cd $VPS_PATH && docker compose -f docker-compose.prod.yml --profile with-monitoring up -d"
    echo "✅ Monitoring services enabled"
    MONITORING_ENABLED=true
else
    echo "⏭️  Skipping monitoring setup"
    MONITORING_ENABLED=false
fi

echo ""

# Step 6: Setup reverse proxy (optional)
echo "🌐 Step 6: Setting up Nginx reverse proxy..."

read -p "Do you want to enable Nginx reverse proxy? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ssh_cmd "cd $VPS_PATH && docker compose -f docker-compose.prod.yml --profile with-nginx up -d"
    echo "✅ Nginx reverse proxy enabled"
    NGINX_ENABLED=true
else
    echo "⏭️  Skipping Nginx setup"
    NGINX_ENABLED=false
fi

echo ""

# Step 7: Final configuration and cleanup
echo "🧹 Step 7: Final cleanup..."

# Clean up old images
ssh_cmd "docker image prune -f"

echo ""

# Show deployment summary
echo "🎉 Docker deployment completed successfully!"
echo ""
echo "📊 Deployment Summary:"
echo "  🌐 Application: http://$VPS_HOST:5000"
echo "  🐘 PostgreSQL: $VPS_HOST:5432"
echo "  🔴 Redis: $VPS_HOST:6379"

if [ "$MONITORING_ENABLED" = true ]; then
    echo "  📊 Prometheus: http://$VPS_HOST:9090"
    echo "  📈 Grafana: http://$VPS_HOST:3000 (admin/admin123)"
fi

if [ "$NGINX_ENABLED" = true ]; then
    echo "  🌐 Nginx Proxy: http://$VPS_HOST (port 80)"
fi

echo ""
echo "🔧 Useful commands on your VPS:"
echo "  Check status:    cd $VPS_PATH && docker compose -f docker-compose.prod.yml ps"
echo "  View logs:       cd $VPS_PATH && docker compose -f docker-compose.prod.yml logs -f"
echo "  Stop services:   cd $VPS_PATH && docker compose -f docker-compose.prod.yml down"
echo "  Restart app:     cd $VPS_PATH && docker compose -f docker-compose.prod.yml restart ai-trading-bot"
echo "  Shell access:    cd $VPS_PATH && docker compose -f docker-compose.prod.yml exec ai-trading-bot bash"
echo ""
echo "🔧 To update the bot later:"
echo "  1. Run this script again, or"
echo "  2. SSH to VPS: ssh $VPS_USER@$VPS_HOST -p $VPS_SSH_PORT"
echo "  3. cd $VPS_PATH && docker-compose -f docker-compose.prod.yml pull && docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo "🚀 Your AI Trading Bot is now running in Docker containers on VPS!"

# Clean up temporary files
rm -f /tmp/deploy.env.production