"""Helpers for assembling runtime context payloads."""
from __future__ import annotations

from typing import Any, Mapping, MutableMapping, Sequence

from app.services import record_user_trade


def build_ai_bot_context_payload(
    *,
    dashboard_data: MutableMapping[str, Any],
    health_data_lock: Any,
    health_report_service: Any,
    indicator_signal_options: Sequence[str],
    indicator_profiles: Sequence[str],
    get_indicator_selection: Any,
    get_all_indicator_selections: Any,
    set_indicator_selection: Any,
    refresh_indicator_dashboard_state: Any,
    ultimate_trader: Any,
    optimized_trader: Any,
    ultimate_ml_system: Any,
    optimized_ml_system: Any,
    futures_ml_system: Any,
    parallel_engine: Any,
    strategy_manager: Any,
    backtest_manager: Any,
    get_active_trading_universe: Any,
    get_real_market_data: Any,
    get_trending_pairs: Any,
    get_user_trader: Any,
    get_user_portfolio_data: Any,
    update_live_portfolio_pnl: Any,
    trade_history: Any,
    apply_binance_credentials: Any,
    get_binance_credential_status: Any,
    binance_credentials_store: Any,
    binance_credential_service: Any,
    binance_log_manager: Any,
    futures_dashboard_state: MutableMapping[str, Any],
    futures_manual_service: Any,
    futures_manual_settings: MutableMapping[str, Any],
    futures_manual_lock: Any,
    futures_data_lock: Any,
    futures_symbols: Sequence[str],
    ensure_futures_manual_defaults: Any,
    trading_config: Mapping[str, Any],
    coerce_bool: Any,
    qfm_engine: Any,
    persistence_manager: Any,
    persistence_scheduler: Any,
    persistence_runtime: Any,
    background_runtime: Any,
    background_task_manager: Any,
    service_runtime: Any,
    realtime_update_service: Any,
    market_data_service: Any,
    futures_market_data_service: Any,
    live_portfolio_scheduler: Any,
    historical_data: MutableMapping[str, Any],
    top_symbols: Sequence[str],
    disabled_symbols: Sequence[str],
    get_all_known_symbols: Any,
    get_disabled_symbols: Any,
    refresh_symbol_counters: Any,
    clear_symbol_from_dashboard: Any,
    is_symbol_disabled: Any,
    disable_symbol: Any,
    enable_symbol: Any,
    save_symbol_state: Any,
    normalize_symbol: Any,
    signal_handler: Any,
    version_label: str,
) -> dict[str, Any]:
    """Build the runtime context payload shared between Flask app and background tasks."""

    return {
        "dashboard_data": dashboard_data,
        "health_data_lock": health_data_lock,
        "health_report_service": health_report_service,
        "indicator_signal_options": indicator_signal_options,
        "indicator_profiles": indicator_profiles,
        "get_indicator_selection": get_indicator_selection,
        "get_all_indicator_selections": get_all_indicator_selections,
        "set_indicator_selection": set_indicator_selection,
        "refresh_indicator_dashboard_state": refresh_indicator_dashboard_state,
        "ultimate_trader": ultimate_trader,
        "optimized_trader": optimized_trader,
        "ultimate_ml_system": ultimate_ml_system,
        "optimized_ml_system": optimized_ml_system,
        "futures_ml_system": futures_ml_system,
        "parallel_engine": parallel_engine,
        "strategy_manager": strategy_manager,
        "backtest_manager": backtest_manager,
        "get_active_trading_universe": get_active_trading_universe,
        "get_real_market_data": get_real_market_data,
        "get_trending_pairs": get_trending_pairs,
        "get_user_trader": get_user_trader,
        "get_user_portfolio_data": get_user_portfolio_data,
        "update_live_portfolio_pnl": update_live_portfolio_pnl,
        "trade_history": trade_history,
        "record_user_trade": record_user_trade,
        "record_user_trade": record_user_trade,
        "apply_binance_credentials": apply_binance_credentials,
        "get_binance_credential_status": get_binance_credential_status,
        "binance_credentials_store": binance_credentials_store,
        "binance_credential_service": binance_credential_service,
        "binance_log_manager": binance_log_manager,
        "futures_dashboard_state": futures_dashboard_state,
        "futures_manual_service": futures_manual_service,
        "futures_manual_settings": futures_manual_settings,
        "futures_manual_lock": futures_manual_lock,
        "futures_data_lock": futures_data_lock,
        "futures_symbols": list(futures_symbols),
        "ensure_futures_manual_defaults": ensure_futures_manual_defaults,
        "trading_config": trading_config,
        "coerce_bool": coerce_bool,
        "qfm_engine": qfm_engine,
        "persistence_manager": persistence_manager,
        "persistence_scheduler": persistence_scheduler,
        "persistence_runtime": persistence_runtime,
        "background_runtime": background_runtime,
        "background_task_manager": background_task_manager,
        "service_runtime": service_runtime,
        "realtime_update_service": realtime_update_service,
        "market_data_service": market_data_service,
        "futures_market_data_service": futures_market_data_service,
        "live_portfolio_scheduler": live_portfolio_scheduler,
        "historical_data": historical_data,
        "top_symbols": list(top_symbols),
        "disabled_symbols": list(disabled_symbols),
        "get_all_known_symbols": get_all_known_symbols,
        "get_disabled_symbols": get_disabled_symbols,
        "refresh_symbol_counters": refresh_symbol_counters,
        "clear_symbol_from_dashboard": clear_symbol_from_dashboard,
        "is_symbol_disabled": is_symbol_disabled,
        "disable_symbol": disable_symbol,
        "enable_symbol": enable_symbol,
        "save_symbol_state": save_symbol_state,
        "normalize_symbol": normalize_symbol,
        "signal_handler": signal_handler,
        "version_label": version_label,
    }


__all__ = ["build_ai_bot_context_payload"]
